----PHONE----

--PRO 15
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE PRO 15','A', 1550000*0.8);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE PRO 15','B', 1550000*0.7);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE PRO 15','C', 1550000*0.6);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE PRO 15','D', 1550000*0.5);

--PRO 14
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE PRO 14','A', 1550000*0.7);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE PRO 14','B', 1550000*0.6);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE PRO 14','C', 1550000*0.5);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE PRO 14','D', 1550000*0.4);

--PRO 13
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE PRO 13','A', 1550000*0.6);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE PRO 13','B', 1550000*0.5);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE PRO 13','C', 1550000*0.4);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE PRO 13','D', 1550000*0.3);

--PRO 12
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE PRO 12','A', 1550000*0.5);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE PRO 12','B', 1550000*0.4);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE PRO 12','C', 1550000*0.3);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE PRO 12','D', 1550000*0.2);

--PRO 11
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE PRO 11','A', 1550000*0.45);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE PRO 11','B', 1550000*0.35);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE PRO 11','C', 1550000*0.25);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE PRO 11','D', 1550000*0.15);

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- 15
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE 15','A', 1250000*0.8);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE 15','B', 1250000*0.7);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE 15','C', 1250000*0.6);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE 15','D', 1250000*0.5);

-- 14
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE 14','A', 1250000*0.7);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE 14','B', 1250000*0.6);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE 14','C', 1250000*0.5);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE 14','D', 1250000*0.4);

-- 13
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE 13','A', 1250000*0.6);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE 13','B', 1250000*0.5);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE 13','C', 1250000*0.4);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE 13','D', 1250000*0.3);

-- 12
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE 12','A', 1250000*0.5);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE 12','B', 1250000*0.4);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE 12','C', 1250000*0.3);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE 12','D', 1250000*0.2);

-- 11
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE 11','A', 1250000*0.45);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE 11','B', 1250000*0.35);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE 11','C', 1250000*0.25);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE 11','D', 1250000*0.15);

-- XS
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE XS','A', 1360000*0.4);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE XS','B', 1360000*0.3);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE XS','C', 1360000*0.2);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'IPHONE XS','D', 1360000*0.1);

-- GALAXY S24

INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'GALAXY S24','A', 1150000*0.8);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'GALAXY S24','B', 1150000*0.7);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'GALAXY S24','C', 1150000*0.6);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'GALAXY S24','D', 1150000*0.5);

-- GALAXY S23

INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'GALAXY S23','A', 1150000*0.7);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'GALAXY S23','B', 1150000*0.6);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'GALAXY S23','C', 1150000*0.5);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'GALAXY S23','D', 1150000*0.4);

-- GALAXY S22

INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'GALAXY S22','A', 1150000*0.6);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'GALAXY S22','B', 1150000*0.5);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'GALAXY S22','C', 1150000*0.4);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'GALAXY S22','D', 1150000*0.3);

-- GALAXY S21

INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'GALAXY S21','A', 1150000*0.5);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'GALAXY S21','B', 1150000*0.4);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'GALAXY S21','C', 1150000*0.3);
INSERT INTO PHONE(NO, MODEL_NAME , GRADE, GRADE_PRICE) VALUES (SEQ_PRICE_SET_NO.NEXTVAL, 'GALAXY S21','D', 1150000*0.2);

COMMIT;