INSERT INTO BATTERY(PERCENTAGE, SCORE) VALUES('90% 이상 100%이하', 0);
INSERT INTO BATTERY(PERCENTAGE, SCORE) VALUES('80% 이상 90%이하', -10);
INSERT INTO BATTERY(PERCENTAGE, SCORE) VALUES('70% 이상 80%이하', -15);
INSERT INTO BATTERY(PERCENTAGE, SCORE) VALUES('60% 이상 70%이하', -20);

COMMIT;

DELETE BATTERY;
