----- MODEL_CLASS -----
INSERT INTO MODEL_CLASS(NO, GRADE, TOTAL_SCORE) VALUES(SEQ_MODEL_CLASST_NO.NEXTVAL, 'A', '90점 이상 100점 미만');
INSERT INTO MODEL_CLASS(NO, GRADE, TOTAL_SCORE) VALUES(SEQ_MODEL_CLASST_NO.NEXTVAL, 'B', '80점 이상 90점 미만');
INSERT INTO MODEL_CLASS(NO, GRADE, TOTAL_SCORE) VALUES(SEQ_MODEL_CLASST_NO.NEXTVAL, 'C', '70점 이상 80점 미만');
INSERT INTO MODEL_CLASS(NO, GRADE, TOTAL_SCORE) VALUES(SEQ_MODEL_CLASST_NO.NEXTVAL, 'D', '60점 이상 70점 미만');
COMMIT;